# This is a basic workflow to help you get started with Actions

name: pytest

# Controls when the workflow will run
on: [push] ## every new commit/merge/push 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: ## the name of the job 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # the os type 
    strategy:
     matrix:
      python-version: [2.7, 3.5, 3.6, 3.7, 3.8] ## the versions of the python environment 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        ## a for loop to setup an environment for each python version 
        with:
          python-version: ${{matrix.python-version}}
      # Runs a set of commands using the runners shell
      - name: INstall dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test with pytest 
        run: |
          pytest 
          
